service: cloudflare-purge-cache-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: '${env:AWS_PROFILE}'
  stage: '${env:AWS_STAGE}'
  timeout: 30
  memorySize: '2048'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'ssm:DescribeParameters'
        - 'ssm:GetParameters'
        - 'ssm:GetParameter'
      Resource:
        - 'arn:aws:ssm:eu-west-1:*:parameter/cloudflare-purge-cache-lambda*'
    - Effect: Allow
      Action:
        - 'kms:Decrypt'
      Resource: '*'
    # SQS
    - Effect: Allow
      Action:
        - 'sqs:*'
      Resource:
        - Fn::GetAtt: [URLsToPurgeQueue, Arn]
        - Fn::GetAtt: [PurgeRequestsAcceptedQueue, Arn]
  environment:
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true
  vpc:
    logRetentionInDays: '14'
    usagePlan:
      quota:
        limit: '5000'
        offset: '2'
        period: MONTH
      throttle:
        burstLimit: '200'
        rateLimit: '100'
  package:
    exclude:
      - .git/**
      - layer/**
      - layer1/**
      - node_modules/**
      - node_modules/**/chrome-aws-lambda/**
  tags:
    ApplicationName: 'cloudflare-purge-cache-lambda'

resources:
  Resources:
    PurgeRequestsAcceptedQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'PurgeRequestsAcceptedQueue'
    URLsToPurgeQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'URLsToPurgeQueue'

functions:
  # Status
  status:
    handler: src/status.handler
    events:
      - http:
          path: status
          method: get
          cors: true
          private: ${self:custom.private.${opt:stage, self:provider.stage}}
    environment:
      PURGE_REQUESTS_ACCEPTED_QUEUE_URL: !Ref PurgeRequestsAcceptedQueue
      PURGE_REQUESTS_ACCEPTED_QUEUE_NAME: PurgeRequestsAcceptedQueue
      URLS_TO_PURGE_QUEUE_URL: !Ref URLsToPurgeQueue
      URLS_TO_PURGE_QUEUE_NAME: URLsToPurgeQueue
  api:
    handler: src/api.handler
    events:
      - http:
          method: POST
          path: '/'
          cors: true
          private: ${self:custom.private.${opt:stage, self:provider.stage}}
    environment:
      PURGE_REQUESTS_ACCEPTED_QUEUE_URL: !Ref PurgeRequestsAcceptedQueue
      PURGE_REQUESTS_ACCEPTED_QUEUE_NAME: PurgeRequestsAcceptedQueue
  browser:
    handler: src/browser.handler
    events:
      - sqs:
          queueName: PurgeRequestsAcceptedQueue
          Fn::GetAtt:
            - PurgeRequestsAcceptedQueue
            - Arn
    environment:
      PURGE_REQUESTS_ACCEPTED_QUEUE_URL: !Ref PurgeRequestsAcceptedQueue
      PURGE_REQUESTS_ACCEPTED_QUEUE_NAME: PurgeRequestsAcceptedQueue
      URLS_TO_PURGE_QUEUE_URL: !Ref URLsToPurgeQueue
      URLS_TO_PURGE_QUEUE_NAME: URLsToPurgeQueue
  cloudflare:
    handler: src/cloudflare.handler
    events:
      - sqs:
          queueName: URLsToPurgeQueue
          Fn::GetAtt:
            - URLsToPurgeQueue
            - Arn

plugins:
  - serverless-cloudside-plugin
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline-dotenv
  - serverless-offline-sqs
  - serverless-offline

custom:
  private:
    Development: false
    Production: true
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  serverless-offline:
    host: 0.0.0.0
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    skipCacheInvalidation: false
